version: '3.9'
services:

  web:
    build: .
    container_name: auth_service
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=0.0.0.0
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_SECRET=${EMAIL_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - Frontend_URL=${Frontend_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - MONGO_URL=${MONGO_URL}
      - MONGODB_NAME=${MONGODB_NAME}
     
      
  db:
    image: postgres:16.3-alpine
    restart: always
    hostname: dbhost
    container_name: gestplay_db
    
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER} 
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 10s
      timeout: 3s
      retries: 3      
    ports:
      - "5432:5432"

